# Server IP Address
SERVER_IP_ADDR: 192.168.0.149
SERVER_PORT: 8000

# Maximum buffer size
MAX_BUF_SIZE: 1024

#In the configuration values below, the right and left values are determined
# based on the direction from the rear of the robot to the front.

ROBOT_NUMBER: "0"

#STEPPER: EN, DIR, STP
# [1]: Right Stepper, [0]: Left Stepper
GPIO_ARM_ENPINS: [2 ,2] # GPIO EN PINS
GPIO_ARM_DIRPINS: [17, 3] # GPIO DIR PINS
GPIO_ARM_STPPINS: [27, 4] # GPIO STEPPER PINS

GPIO_SERVO_PIN: 22 # GPIO DIR PINS

#EncoderMotor: dir, pwm, start, encA, encB
RIGHT_WHEEL_PINS: [1,12,16,20,21] 
LEFT_WHEEL_PINS: [19,13,6,5,0]

#EncoderMotor config
ENC_PULSE_PER_CYCLE: 13
MOTOR_WHEEL_GEAR: 51
WHEEL_SIZE: 95
MAX_MOVE_CONTROL_DIST: 1000
MAX_ROTATE_CONTROL_ANGLE: 90

# C_Motor Configurations
MOTOR_ARM_ANG_PER_STEP: 0.1125
MOTOR_ARM_GEAR: [50.0,10.0]

#Robot Arm config for initialize and motion control
ROBOTARM_L1 : 154
ROBOTARM_L2 : 180
ROBOTARM_MAX_WORKING_DIST : 308.62
ROBOTARM_MAX_ANGLES : [360.0,360.0]
ROBOTARM_MIN_ANGLES : [-0.1,-0.1]
ROBOT_ARM_BEFORE_WORK : 100
ROBOT_ARM_CENTER_HEIGHT : 154.458
ROBOT_ARM_CENTER_DIST : 111.0
ROBOT_ARM_GRIPPER_HEIGHT : 65
ROBOT_ARM_GRIPPER_DIST : 85

#ROBOT Arm Postions for stacking and lifting
ROBOTARM_INITIAL_POSITION : [65.011,266.55]
ROBOTARM_INITIAL_ANGLE : [90.0, 90.0]
ROBOT_ARM_MOVING_POSITION : [60.0,260.0]

#PID Gain Values and Allowable error range(in mm for move, in angle (360) for rotation)
MOVE_KP: 0.25
MOVE_KI: 0.0006
MOVE_KD: 0.036
MOVE_TOLERANCE: 20

ROTATION_KP: 1.2
ROTATION_KI: 0.03
ROTATION_KD: 0.9
ROTATION_TOLERANCE: 5

#PID Gain Values and Allowable error range for accurate moving before lifting or stacking
MOVE_ACC_KP: 2
MOVE_ACC_KI: 1.5
MOVE_ACC_KD: 2
MOVE_ACC_TOLERANCE: 5

ROTATION_ACC_KP: 2
ROTATION_ACC_KI: 1.5
ROTATION_ACC_KD: 2
ROTATION_ACC_TOLERANCE: 5